name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b0b6efed53548e52bd99db1e3a7095b4f6b62511da3f41ac9ae2edfb49a9fbc"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
