name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3b851a9de42a742ce6a5feb9582a9298f4dc435902258207c187fe9b876ace4"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
