name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8935e8f00dd1797dd7235e11d1e855d7a8948c1bce0c4e98ddbc0d09729eabb8"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
